{{- if .Values.ingress.enabled -}}
{{- $fullName := include "helloworld.fullname" . -}}
{{- $ingressPaths := .Values.ingress.paths -}}
{{- $ingressPathType := .Values.ingress.pathType -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app.kubernetes.io/name: {{ include "helloworld.name" . }}
    helm.sh/chart: {{ include "helloworld.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
	{{- range $ingressPaths }}
          - pathType: {{ $ingressPathType }}
            path: {{ . }}
            backend:
              service:
                Name: {{ $fullName }}
                port:
                  number: 80
	{{- end }}
  {{- end }}
{{- end }}
