apiVersion: v1
kind: Pod
metadata:
  labels:
    app: load-generator
  name: load-generator
spec:
  containers:
  - name: load-generator
    image: busybox
    imagePullPolicy: Always
    args:
    - /bin/sh
    - -c
    - sleep 120;
      echo "sleep 5";
      for i in `seq 1 10`; do wget -q -O- http://php-apache; sleep 5; done;
      echo "sleep 0.01";
      for i in `seq 1 1200`; do wget -q -O- http://php-apache; sleep 0.01; done;
      echo "sleep 1";
      for i in `seq 1 300`; do wget -q -O- http://php-apache; sleep 1; done;
      echo "sleep 5";
      for i in `seq 1 10`; do wget -q -O- http://php-apache; sleep 5; done;
      echo "finito";

    resources: {}
  restartPolicy: Never
