apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: autoscaler-example
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: {{ .Values.argoNamespace | default "argocd" }}
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: teams/autoscaler-example/dev
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
