apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubedb
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: kubedb
    server: {{ .Values.spec.destination.server }}
  source:
    chart: kubedb
    repoURL: https://charts.appscode.com/stable
    targetRevision: v2024.1.31
    helm:
      valuesObject:
        global:
          license: |
            -----BEGIN CERTIFICATE-----
            MIIEVzCCAz+gAwIBAgIIN9Gl1gieIOAwDQYJKoZIhvcNAQELBQAwJTEWMBQGA1UE
            ChMNQXBwc0NvZGUgSW5jLjELMAkGA1UEAxMCY2EwHhcNMjQwMjE3MDcyMDQ3WhcN
            MjQwMzE4MDcyMDQ3WjCCARgxDzANBgNVBAYTBmt1YmVkYjETMBEGA1UECBMKZW50
            ZXJwcmlzZTGBpDAXBgNVBAoTEGt1YmVkYi1jb21tdW5pdHkwFwYDVQQKExBrdWJl
            ZGItZXh0LXN0YXNoMBgGA1UEChMRa3ViZWRiLWF1dG9zY2FsZXIwGAYDVQQKExFr
            dWJlZGItZW50ZXJwcmlzZTAcBgNVBAoTFXBhbm9wdGljb24tZW50ZXJwcmlzZTAe
            BgNVBAoTF2t1YmVkYi1tb25pdG9yaW5nLWFnZW50MRowGAYDVQQLExFrdWJlZGIt
            ZW50ZXJwcmlzZTEtMCsGA1UEAxMkMWRlNDkxNWUtMzFlNy00NDFmLWE1ZWMtYTJk
            YWFiMjRmMWM0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArzPqwaUI
            8oX/HKhnS5ZFEBEXJD9LDFMC0OUxUuHKDLyQUJQHJBMB/Pg1500ICkHUf+OeHaY3
            8xn26k7345n358tXe47pxZ4+MEWeAF5LPlAuaayIlsFWtilqQt7LRWyMXReXLLAw
            oFPO210d8eZ4mVHrOLVHAjHE3ENi47Uxukg9JwHQgr7W/rDWUrP62k5IALpJutUF
            cqLsrEqePqTbkGzDVaZzzca3I+spSsuRa8zPkzhQ1zNDbqO+HdIGNKZWe4PetwRp
            qW3bHjtSay/A9e7MKe+rviP0kseeDbl8vhd7QCibHUoWncWNp6koCQKlPk7taHWc
            Hd8LD4fvHo2WLwIDAQABo4GVMIGSMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAK
            BggrBgEFBQcDAjBrBgNVHREEZDBigiQxZGU0OTE1ZS0zMWU3LTQ0MWYtYTVlYy1h
            MmRhYWIyNGYxYzSBIlZpbmNlIFRzZSA8dnRzZStrdWJlZGJAYW1hem9uLmNvbT6B
            FnZ0c2Ura3ViZWRiQGFtYXpvbi5jb20wDQYJKoZIhvcNAQELBQADggEBAC1mcSAf
            T1CT1dU+R+HI76ccLJBgXK3Q99q+ZdS9QAAQ+7PILd5pWNs5caTXTbjdDyxf1Hub
            FyYbe5sd6o6hw16mH67zudFCVSZl+j6RUL6iglPtb3RaqXa+jfwqk9TrcSUnP55b
            fj/cc6VqHv8giGCOSmLoVLxfchZETfDUy9E8Pps0h9ZNqkL+QVxU042bAU69rWz6
            Z9RjdB5SKprW87PDLikGN4A00SpbRM1c0GuZYgjpYZn8mnrxS0eAGE3DY3R8gkkt
            lUzCoi8LrYkEJ19SDqBeKX5fz7S07otK8MkigZ5kG46GWVkFuFmw5/COtrNVt2tJ
            qTi6JCvudwI81Tk=
            -----END CERTIFICATE-----
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    namespace: demo
  - group: admissionregistration.k8s.io
    jsonPointers:
    - /webhooks/clientConfig/caBundle
    kind: MutatingWebhookConfiguration
    namespace: ""
  - group: admissionregistration.k8s.io
    jsonPointers:
    - /webhooks/clientConfig/caBundle
    kind: ValidatingWebhookConfiguration
    namespace: ""
