apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubedb
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: kubedb
    server: {{ .Values.spec.destination.server }}
  source:
    chart: kubedb
    repoURL: https://charts.appscode.com/stable
    targetRevision: v2024.9.30
    helm:
      valuesObject:
        global:
          license: |
            -----BEGIN CERTIFICATE-----
            MIIEZTCCA02gAwIBAgIIKP3NIcSgfJAwDQYJKoZIhvcNAQELBQAwJTEWMBQGA1UE
            ChMNQXBwc0NvZGUgSW5jLjELMAkGA1UEAxMCY2EwHhcNMjQxMDExMjMwMDQ3WhcN
            MjQxMTEwMjMwMDQ3WjCCARgxDzANBgNVBAYTBmt1YmVkYjETMBEGA1UECBMKZW50
            ZXJwcmlzZTGBpDAXBgNVBAoTEGt1YmVkYi1jb21tdW5pdHkwFwYDVQQKExBrdWJl
            ZGItZXh0LXN0YXNoMBgGA1UEChMRa3ViZWRiLWF1dG9zY2FsZXIwGAYDVQQKExFr
            dWJlZGItZW50ZXJwcmlzZTAcBgNVBAoTFXBhbm9wdGljb24tZW50ZXJwcmlzZTAe
            BgNVBAoTF2t1YmVkYi1tb25pdG9yaW5nLWFnZW50MRowGAYDVQQLExFrdWJlZGIt
            ZW50ZXJwcmlzZTEtMCsGA1UEAxMkZjA4NzRmYTEtYzcyNy00NWJjLTg1OWUtMzc0
            NDQ5MWRkYTZiMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuKyzVuWv
            IIH5ImrS6LovSsQd1sgpNQX08FY7RBESwEWC2MEKjUcvxh10zaOE3PIdFtAY/bj+
            nBbHqT6FgwwRF9sQv7EjnUBi5Qbo4XU9Z6pwIcXaBv5zFtyQF43oQ0Gly5Nb1FYi
            d3FPNqpQ5QEXjtVfpKDnDE64FCSe4KKxNk3rMSlCyXkbRu+0qmkYuJXcvQjQchy8
            nFuhIT56PgWkd7yjo8lWqRp3xVC9o0R+2ALNJk0sJwyaXMQjlkxoy6rnsVHPYIr/
            YyDOTpu4Mcma+h0ue3jCVSrighY0/fjiEZR3ov+GerQD7M6Lxm9zz5k2Vreu8jXH
            FwVktXbOmlhlNQIDAQABo4GjMIGgMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAK
            BggrBgEFBQcDAjAfBgNVHSMEGDAWgBTZMREkIF69G3qzMCLSm9DzksSgeTBYBgNV
            HREEUTBPgiRmMDg3NGZhMS1jNzI3LTQ1YmMtODU5ZS0zNzQ0NDkxZGRhNmKBFnZ0
            c2UgPHZ0c2VAYW1hem9uLmNvbT6BD3Z0c2VAYW1hem9uLmNvbTANBgkqhkiG9w0B
            AQsFAAOCAQEAkQ18rDFltV3YsFQ+sl204u8Z5RUaHUUfAIKLtItkoIg9gPtpYATa
            EljxKVT4ZIXiosNBC8vHzXZE8E4N/VlpTnSN8nz4SbtLYCVgKJlWAE7H5Sh9IDpx
            VgS/y3u0jswvQNVL6Ma+C50pDlFnOfD6xEyDOZlozDNEhLIDX8a3jRDzseGyS7ry
            U8NRZhcFGhXXnHjcqtfr3f7JdKdXrdURjZt2pOIVhJ1PnBhcg6FHQVWI9DjiPsF9
            N17+KaaO4gtWmG9+vPc7AYfxPGlmPY8Dj/HRl9hQ2VUQ8IxrEyh0KPx4aPmINhLQ
            yxgGUVdbxRWzEGUPnnxm2aW4xIsCdfiTPg==
            -----END CERTIFICATE-----
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data
    kind: Secret
    namespace: demo
  - group: admissionregistration.k8s.io
    jsonPointers:
    - /webhooks/clientConfig/caBundle
    kind: MutatingWebhookConfiguration
    namespace: ""
  - group: admissionregistration.k8s.io
    jsonPointers:
    - /webhooks/clientConfig/caBundle
    kind: ValidatingWebhookConfiguration
    namespace: ""
