apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubedb-postgres
  namespace: demo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: demo
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: teams/kubedb-postgres/dev
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
