apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubedb
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: kubedb
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: oci://ghcr.io/appscode-charts
    chart: kubedb
    targetRevision: v2024.1.31
    helm:
      valueFiles:
      - "../kubedb-license.yaml"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
